# Generated by Django 5.1.4 on 2025-01-02 05:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('new_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
