# Generated by Django 5.1.4 on 2025-01-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsP', '0003_alter_post_managers_remove_post_banner_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_path',
            field=models.ImageField(default=2024, upload_to='news_bannner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='newsP.category'),
        ),
    ]
